# Generated by Django 4.2.17 on 2024-12-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="end_month",
            field=models.IntegerField(
                choices=[(3, "March"), (5, "May")],
                default=3,
                help_text="Month when academic year ends",
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="start_month",
            field=models.IntegerField(
                choices=[(4, "April"), (6, "June")],
                default=4,
                help_text="Month when academic year starts",
            ),
        ),
    ]
