# Generated by Django 4.2.17 on 2024-12-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("academic", "0002_academicyear_end_month_academicyear_start_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="core.school",
            ),
            preserve_default=False,
        ),
    ]
