# Generated by Django 4.2.17 on 2024-12-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("academic", "0003_academicyear_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="core.school",
            ),
        ),
    ]
