# Generated by Django 4.2.17 on 2024-12-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_school_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="auto_create_schema",
            field=models.BooleanField(
                default=True,
                help_text="If True, schema will be automatically created and synced when school is saved",
            ),
        ),
    ]
