# Generated by Django 4.2.17 on 2024-12-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feecategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("tuition", "Tuition Fee"),
                    ("exam", "Examination Fee"),
                    ("transport", "Transport Fee"),
                    ("library", "Library Fee"),
                    ("other", "Other Fee"),
                ],
                default="tuition",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feecategory",
            name="is_optional",
            field=models.BooleanField(
                default=False, help_text="Whether this fee is optional"
            ),
        ),
    ]
