# Generated by Django 4.2.17 on 2024-12-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="O",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_email",
            field=models.EmailField(
                default="update-required@example.com", max_length=254
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_name",
            field=models.CharField(default="Update Required", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_phone",
            field=models.CharField(default="0000000000", max_length=20),
            preserve_default=False,
        ),
    ]
