# Generated by Django 4.2.17 on 2024-12-30 13:34

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_school_alter_studentprofile_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
